FROM python:3.11-slim

WORKDIR /app 

COPY requirements.txt requirements.txt
RUN apt-get update && apt-get install -y --no-install-recommends build-essential pkg-config libmariadb-dev && rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

COPY . /app
